
GET http://localhost:3001/getBlogPosts

####

POST http://localhost:3001/createBlogPost HTTP/1.1
Content-Type: application/json

{
    "title": "Tuplone",
    "postDate": "1 Gennaio 2034",
    "avatar": "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png"
}

####

POST http://localhost:3001/660435d6eb346efc95454746/comments HTTP/1.1
Content-Type: application/json

{
  "text": "Prova commento",
  "author": "io"
}

####

GET http://localhost:3001/660435d6eb346efc95454746/comments

####

GET http://localhost:3001/getBlogPosts/65fea939a3ee71cdb1f2b94e

####

PATCH http://localhost:3001/updateBlogPost/65fea939a3ee71cdb1f2b94e
Content-Type: application/json

  {
    "firstName": "Topolino"
  }

####

DELETE http://localhost:3001/deleteBlogPost/660445f132c63d3bd6658aa4