
GET http://localhost:3001/getUsers

####

POST http://localhost:3001/createUser
Content-Type: application/json

{
    "firstName": "Angelo",
    "lastName": "Giuliano",
    "email": "prova@prova.it",
    "password": "ciao1234",
    "age": 21
}

####

DELETE http://localhost:3001/deleteUser/660154720ad749cee7065692